=== History

* August 25, 2015
** 3.0.0.M1 release
* November 17, 2014
** 2.0-RC2 release
* October 08, 2013
** 2.0-RC1 release
* August 20, 2012
** 1.1.1 release
* February 16, 2011
** 1.1 release
* February 7, 2011
** 1.0.2 release
* August 1, 2010
** 1.0.1 release
* July 27, 2010
** 1.0 release
* May 22, 2010
** initial 0.1 release

=== Authors

Burt Beckwith

=== Previous work

Stephan February did the http://blog.bruary.net/2008/04/grails-acegi-acl-howto.html[first work] adding ACL support to the http://grails.org/plugin/acegi/[Acegi] plugin. At the time the plugin was based on Acegi 1.0.x and around the same time the plugin was converted to use Spring Security 2.0 and the ACL support wasn't converted to use the new package layout and approach.

Work was done in 2009 to create a GORM-based implementation (the standard Spring Security implementation uses JDBC). Around the same time, Phillip Merensky http://grails.1312388.n4.nabble.com/Acegi-Plugin-0-5-1-with-ACL-support-implemented-td1400650.html[mentioned on the Grails mailing list] that he was working on an implementation. He wrote about his approach http://imagesiteproject.wordpress.com/2009/09/24/integration-of-spring-security-into-grails-plugin-approach-3/[here] and this was merged in with the other approach but never formally released.

This plugin builds on that work but is based on Spring Security 4 and Spring 4.
